export const featuredCars = [
  {
    id: "1",
    make: "Toyota",
    model: "Vitz",
    year: 2022,
    price: 11900,
    image: "/car-images/arteon1.jpg",
  },
  {
    id: "2",
    make: "Honda",
    model: "Fit",
    year: 2021,
    price: 11300,
    image: "/car-images/sienta2.jpg",
  },
  {
    id: "3",
    make: "Mazda",
    model: "Demio",
    year: 2020,
    price: 12500,
    image: "/car-images/vitz1.jpg",
  },
  {
    id: "4",
    make: "Subaru",
    model: "Forester",
    year: 2023,
    price: 23900,
    image: "/car-images/impreza1.jpg",
  },
  {
    id: "5",
    make: "Nissan",
    model: "Note",
    year: 2021,
    price: 9800,
    image: "/car-images/note1.jpg",
  },
  {
    id: "6",
    make: "Volkswagen",
    model: "Golf",
    year: 2022,
    price: 17900,
    image: "/car-images/arteon2.jpg",
  },
  {
    id: "7",
    make: "BMW",
    model: "X3",
    year: 2020,
    price: 34000,
    image: "/car-images/arteon2.jpg",
  },
  {
    id: "8",
    make: "Mercedes-Benz",
    model: "C200",
    year: 2021,
    price: 37900,
    image: "/car-images/impreza3.jpg",
  },
  {
    id: "9",
    make: "Toyota",
    model: "Harrier",
    year: 2023,
    price: 26500,
    image: "/car-images/note3.jpg",
  },
  {
    id: "10",
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    price: 42000,
    image: "/car-images/notewhite4.jpg",
  },
  {
    id: "11",
    make: "Suzuki",
    model: "Swift",
    year: 2024,
    price: 4000,
    image: "/car-images/demio3.jpg",
  },
];
